# nome da pipeline
name: Pipeline CI

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch
# gatilho por push
# gatilho agendado = schedule

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
  
  schedule:
    - cron: '59 23 * * 0'       # todo domingo às 23:59 horario UTC ou domingo às 20:59 horario de Brasília

#tarefas dentro da pipeline = jobs
jobs:
  #nome do job
  testes:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # instalando dependencias
      - name: Instalando dependencias
        run: npm install  

      # Rodando e gerando relatório de testes
      - name: Rodando os testes
        run: npm test

      # Publicar relatorio: cria download .zip > extrai arquivo > abre .html no navegador
      - name: Publicar Report de testes
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./test-reports/
          retention-days: 30